/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXEC_H_RPCGEN
#define _EXEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define EXECSH 0x12345678
#define EXECSH_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define EXEC_STRING 1
extern  char ** exec_string_1(char **, CLIENT *);
extern  char ** exec_string_1_svc(char **, struct svc_req *);
extern int execsh_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXEC_STRING 1
extern  char ** exec_string_1();
extern  char ** exec_string_1_svc();
extern int execsh_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXEC_H_RPCGEN */
